export default {
    bubbleFactory: {
        display: 'flex',
        height: '10vh',
        border: 'solid 1px black',
        flexDirection: 'column',
        padding: '12px',
        cursor: 'pointer',
    },
    bubbleFactoryInfo: {
        display: 'flex',
        flex: 6,
    },
    bubbleFactoryTitle: {
        display: 'flex',
        fontWeight: 'bold',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        fontSize: '24pt',
        flex: 6,
    },
    mobileBubbleFactoryTitle: {
        display: 'flex',
        fontWeight: 'bold',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        fontSize: '16pt',
        flex: 7,
    },
    bubbleFactoryCount: {
        display: 'flex',
        flex: 6,
        justifyContent: 'flex-end',
        alignItems: 'flex-start',
        fontSize: '24pt',
    },
    mobileBubbleFactoryCount: {
        display: 'flex',
        flex: 5,
        justifyContent: 'flex-end',
        alignItems: 'flex-start',
        fontSize: '16pt',
    },
    bubbleFactoryRate: {
        display: 'flex',
        flex: 6,
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
        fontSize: '20pt',
    },
    mobileBubbleFactoryRate: {
        display: 'flex',
        flex: 6,
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
        fontSize: '12pt',
    },
    bubbleFactoryCost: {
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        fontSize: '16pt',
        flex: 6,
    },
    mobileBubbleFactoryCost: {
        display: 'flex',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        fontSize: '12pt',
        flex: 6,
    }
};
